name: untils-selfhosted

services:
  server:
    image: ghcr.io/alexpls/untils:latest
    ports:
      - "3322:3322"
    env_file:
      - .env.selfhosted
    environment:
      PG_URL: postgresql://${DB_USERNAME}:${DB_PASSWORD}@db:5432/${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA_LOCATION:-./tmp/selfhosted_pgdata}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d postgres"]
      interval: 3s
      timeout: 3s
      retries: 20

  browser:
    image: chromedp/headless-shell:latest
    shm_size: 2G
