// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: monitors.sql

package sqlc

import (
	"context"
	"time"

	"github.com/alexpls/untils_go/internal/llm"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendConfirmingCheckIDToResult = `-- name: AppendConfirmingCheckIDToResult :exec
update monitor_results
set confirming_check_ids = array_append(confirming_check_ids, $1::bigint),
    latest_confirmation_at = now()
where id = $2
`

type AppendConfirmingCheckIDToResultParams struct {
	ConfirmingCheckIDToAppend int64
	MonitorResultID           int64
}

func (q *Queries) AppendConfirmingCheckIDToResult(ctx context.Context, db DBTX, arg *AppendConfirmingCheckIDToResultParams) error {
	_, err := db.Exec(ctx, appendConfirmingCheckIDToResult, arg.ConfirmingCheckIDToAppend, arg.MonitorResultID)
	return err
}

const bumpMonitorVersion = `-- name: BumpMonitorVersion :exec
update monitors set updated_at = now() where id = $1
`

func (q *Queries) BumpMonitorVersion(ctx context.Context, db DBTX, monitorID int64) error {
	_, err := db.Exec(ctx, bumpMonitorVersion, monitorID)
	return err
}

const createMonitor = `-- name: CreateMonitor :one
insert into monitors (user_id, subject, instructions, status, updated_at, created_at)
values ($1, $2, $3, 'validating', now(), now())
returning id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert
`

type CreateMonitorParams struct {
	UserID       int64
	Subject      pgtype.Text
	Instructions pgtype.Text
}

func (q *Queries) CreateMonitor(ctx context.Context, db DBTX, arg *CreateMonitorParams) (*Monitor, error) {
	row := db.QueryRow(ctx, createMonitor, arg.UserID, arg.Subject, arg.Instructions)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subject,
		&i.Instructions,
		&i.RejectedReason,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Expert,
	)
	return &i, err
}

const createMonitorCheck = `-- name: CreateMonitorCheck :one
insert into monitor_checks (monitor_id, status, scheduled_for, done_at)
values ($1, $2, $3, $4)
returning id, monitor_id, status, scheduled_for, failure_reason, done_at
`

type CreateMonitorCheckParams struct {
	MonitorID    int64
	Status       MonitorCheckStatus
	ScheduledFor time.Time
	DoneAt       *time.Time
}

func (q *Queries) CreateMonitorCheck(ctx context.Context, db DBTX, arg *CreateMonitorCheckParams) (*MonitorCheck, error) {
	row := db.QueryRow(ctx, createMonitorCheck,
		arg.MonitorID,
		arg.Status,
		arg.ScheduledFor,
		arg.DoneAt,
	)
	var i MonitorCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.ScheduledFor,
		&i.FailureReason,
		&i.DoneAt,
	)
	return &i, err
}

const createMonitorNotifier = `-- name: CreateMonitorNotifier :one
insert into monitor_notifiers (monitor_id, type, created_at)
values ($1, $2, now())
returning id, monitor_id, type, created_at
`

type CreateMonitorNotifierParams struct {
	MonitorID int64
	Type      Notifier
}

func (q *Queries) CreateMonitorNotifier(ctx context.Context, db DBTX, arg *CreateMonitorNotifierParams) (*MonitorNotifier, error) {
	row := db.QueryRow(ctx, createMonitorNotifier, arg.MonitorID, arg.Type)
	var i MonitorNotifier
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Type,
		&i.CreatedAt,
	)
	return &i, err
}

const createMonitorResult = `-- name: CreateMonitorResult :one
insert into monitor_results (monitor_id, confirming_check_ids, result, date, date_past_tense_verb, citations, latest_confirmation_at, created_at)
values ($1, $2, $3, $4, $5, $6, now(), now())
returning id, monitor_id, confirming_check_ids, result, date, date_past_tense_verb, citations, latest_confirmation_at, created_at
`

type CreateMonitorResultParams struct {
	MonitorID          int64
	ConfirmingCheckIds []int64
	Result             string
	Date               *time.Time
	DatePastTenseVerb  pgtype.Text
	Citations          *llm.Citations
}

func (q *Queries) CreateMonitorResult(ctx context.Context, db DBTX, arg *CreateMonitorResultParams) (*MonitorResult, error) {
	row := db.QueryRow(ctx, createMonitorResult,
		arg.MonitorID,
		arg.ConfirmingCheckIds,
		arg.Result,
		arg.Date,
		arg.DatePastTenseVerb,
		arg.Citations,
	)
	var i MonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ConfirmingCheckIds,
		&i.Result,
		&i.Date,
		&i.DatePastTenseVerb,
		&i.Citations,
		&i.LatestConfirmationAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteMonitor = `-- name: DeleteMonitor :exec
delete from monitors
where user_id = $1 and id = $2
`

type DeleteMonitorParams struct {
	UserID    int64
	MonitorID int64
}

func (q *Queries) DeleteMonitor(ctx context.Context, db DBTX, arg *DeleteMonitorParams) error {
	_, err := db.Exec(ctx, deleteMonitor, arg.UserID, arg.MonitorID)
	return err
}

const deleteMonitorChecks = `-- name: DeleteMonitorChecks :exec
delete from monitor_checks
where monitor_id = $1
`

func (q *Queries) DeleteMonitorChecks(ctx context.Context, db DBTX, monitorID int64) error {
	_, err := db.Exec(ctx, deleteMonitorChecks, monitorID)
	return err
}

const deleteMonitorNotifier = `-- name: DeleteMonitorNotifier :exec
delete from monitor_notifiers
where monitor_id = $1 and type = $2
`

type DeleteMonitorNotifierParams struct {
	MonitorID int64
	Type      Notifier
}

func (q *Queries) DeleteMonitorNotifier(ctx context.Context, db DBTX, arg *DeleteMonitorNotifierParams) error {
	_, err := db.Exec(ctx, deleteMonitorNotifier, arg.MonitorID, arg.Type)
	return err
}

const deleteMonitorNotifiersByUserAndType = `-- name: DeleteMonitorNotifiersByUserAndType :exec
delete from monitor_notifiers
where type = $1
and monitor_id in (select id from monitors where user_id = $2)
`

type DeleteMonitorNotifiersByUserAndTypeParams struct {
	Type   Notifier
	UserID int64
}

func (q *Queries) DeleteMonitorNotifiersByUserAndType(ctx context.Context, db DBTX, arg *DeleteMonitorNotifiersByUserAndTypeParams) error {
	_, err := db.Exec(ctx, deleteMonitorNotifiersByUserAndType, arg.Type, arg.UserID)
	return err
}

const deleteMonitorResults = `-- name: DeleteMonitorResults :exec
delete from monitor_results
where monitor_id = $1
`

func (q *Queries) DeleteMonitorResults(ctx context.Context, db DBTX, monitorID int64) error {
	_, err := db.Exec(ctx, deleteMonitorResults, monitorID)
	return err
}

const getLatestMonitorResult = `-- name: GetLatestMonitorResult :one
select id, monitor_id, confirming_check_ids, result, date, date_past_tense_verb, citations, latest_confirmation_at, created_at from monitor_results
where monitor_id = $1
order by created_at desc
limit 1
`

func (q *Queries) GetLatestMonitorResult(ctx context.Context, db DBTX, monitorID int64) (*MonitorResult, error) {
	row := db.QueryRow(ctx, getLatestMonitorResult, monitorID)
	var i MonitorResult
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.ConfirmingCheckIds,
		&i.Result,
		&i.Date,
		&i.DatePastTenseVerb,
		&i.Citations,
		&i.LatestConfirmationAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getMonitor = `-- name: GetMonitor :one
select id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert from monitors
where user_id = $1 and id = $2
`

type GetMonitorParams struct {
	UserID int64
	ID     int64
}

func (q *Queries) GetMonitor(ctx context.Context, db DBTX, arg *GetMonitorParams) (*Monitor, error) {
	row := db.QueryRow(ctx, getMonitor, arg.UserID, arg.ID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subject,
		&i.Instructions,
		&i.RejectedReason,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Expert,
	)
	return &i, err
}

const getMonitorCheck = `-- name: GetMonitorCheck :one
select id, monitor_id, status, scheduled_for, failure_reason, done_at from monitor_checks
where id = $1
`

func (q *Queries) GetMonitorCheck(ctx context.Context, db DBTX, id int64) (*MonitorCheck, error) {
	row := db.QueryRow(ctx, getMonitorCheck, id)
	var i MonitorCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.ScheduledFor,
		&i.FailureReason,
		&i.DoneAt,
	)
	return &i, err
}

const getNextMonitorCheck = `-- name: GetNextMonitorCheck :one
select id, monitor_id, status, scheduled_for, failure_reason, done_at from monitor_checks
where monitor_id = $1
and (status = 'scheduled' or status = 'checking')
order by scheduled_for desc
limit 1
`

func (q *Queries) GetNextMonitorCheck(ctx context.Context, db DBTX, monitorID int64) (*MonitorCheck, error) {
	row := db.QueryRow(ctx, getNextMonitorCheck, monitorID)
	var i MonitorCheck
	err := row.Scan(
		&i.ID,
		&i.MonitorID,
		&i.Status,
		&i.ScheduledFor,
		&i.FailureReason,
		&i.DoneAt,
	)
	return &i, err
}

const listMonitorNotifiers = `-- name: ListMonitorNotifiers :many
select id, monitor_id, type, created_at from monitor_notifiers
where monitor_id = $1
order by created_at desc
`

func (q *Queries) ListMonitorNotifiers(ctx context.Context, db DBTX, monitorID int64) ([]*MonitorNotifier, error) {
	rows, err := db.Query(ctx, listMonitorNotifiers, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MonitorNotifier
	for rows.Next() {
		var i MonitorNotifier
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitorResults = `-- name: ListMonitorResults :many
select id, monitor_id, confirming_check_ids, result, date, date_past_tense_verb, citations, latest_confirmation_at, created_at from monitor_results
where monitor_id = $1
order by created_at desc
`

func (q *Queries) ListMonitorResults(ctx context.Context, db DBTX, monitorID int64) ([]*MonitorResult, error) {
	rows, err := db.Query(ctx, listMonitorResults, monitorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*MonitorResult
	for rows.Next() {
		var i MonitorResult
		if err := rows.Scan(
			&i.ID,
			&i.MonitorID,
			&i.ConfirmingCheckIds,
			&i.Result,
			&i.Date,
			&i.DatePastTenseVerb,
			&i.Citations,
			&i.LatestConfirmationAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMonitors = `-- name: ListMonitors :many
select id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert from monitors
where user_id = $1 and status = 'active'
order by created_at desc
`

func (q *Queries) ListMonitors(ctx context.Context, db DBTX, userID int64) ([]*Monitor, error) {
	rows, err := db.Query(ctx, listMonitors, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Monitor
	for rows.Next() {
		var i Monitor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Subject,
			&i.Instructions,
			&i.RejectedReason,
			&i.UpdatedAt,
			&i.CreatedAt,
			&i.Expert,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectMonitor = `-- name: RejectMonitor :exec
update monitors
set status = 'rejected',
    rejected_reason = $1,
    updated_at = now()
where user_id = $2 and id = $3
`

type RejectMonitorParams struct {
	RejectedReason pgtype.Text
	UserID         int64
	ID             int64
}

func (q *Queries) RejectMonitor(ctx context.Context, db DBTX, arg *RejectMonitorParams) error {
	_, err := db.Exec(ctx, rejectMonitor, arg.RejectedReason, arg.UserID, arg.ID)
	return err
}

const skipPendingChecks = `-- name: SkipPendingChecks :exec
update monitor_checks
set status = 'skipped'
where monitor_id = $1
and status in ('scheduled', 'checking')
`

func (q *Queries) SkipPendingChecks(ctx context.Context, db DBTX, monitorID int64) error {
	_, err := db.Exec(ctx, skipPendingChecks, monitorID)
	return err
}

const updateMonitorCheckChecking = `-- name: UpdateMonitorCheckChecking :exec
update monitor_checks
set status = 'checking'
where id = $1
`

func (q *Queries) UpdateMonitorCheckChecking(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, updateMonitorCheckChecking, id)
	return err
}

const updateMonitorCheckFailed = `-- name: UpdateMonitorCheckFailed :exec
update monitor_checks
set status = 'failed', failure_reason = $1, done_at = now()
where id = $2
`

type UpdateMonitorCheckFailedParams struct {
	FailureReason pgtype.Text
	ID            int64
}

func (q *Queries) UpdateMonitorCheckFailed(ctx context.Context, db DBTX, arg *UpdateMonitorCheckFailedParams) error {
	_, err := db.Exec(ctx, updateMonitorCheckFailed, arg.FailureReason, arg.ID)
	return err
}

const updateMonitorCheckSuccess = `-- name: UpdateMonitorCheckSuccess :exec
update monitor_checks
set status = 'success', done_at = now()
where id = $1
`

func (q *Queries) UpdateMonitorCheckSuccess(ctx context.Context, db DBTX, id int64) error {
	_, err := db.Exec(ctx, updateMonitorCheckSuccess, id)
	return err
}

const updateMonitorDraft = `-- name: UpdateMonitorDraft :one
update monitors
set subject = $1, instructions = $2, updated_at = now()
where user_id = $3 and id = $4 and status != 'active'
returning id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert
`

type UpdateMonitorDraftParams struct {
	Subject      pgtype.Text
	Instructions pgtype.Text
	UserID       int64
	ID           int64
}

func (q *Queries) UpdateMonitorDraft(ctx context.Context, db DBTX, arg *UpdateMonitorDraftParams) (*Monitor, error) {
	row := db.QueryRow(ctx, updateMonitorDraft,
		arg.Subject,
		arg.Instructions,
		arg.UserID,
		arg.ID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subject,
		&i.Instructions,
		&i.RejectedReason,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Expert,
	)
	return &i, err
}

const updateMonitorStatus = `-- name: UpdateMonitorStatus :one
update monitors
set status = $1, updated_at = now()
where user_id = $2 and id = $3
returning id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert
`

type UpdateMonitorStatusParams struct {
	Status MonitorStatus
	UserID int64
	ID     int64
}

func (q *Queries) UpdateMonitorStatus(ctx context.Context, db DBTX, arg *UpdateMonitorStatusParams) (*Monitor, error) {
	row := db.QueryRow(ctx, updateMonitorStatus, arg.Status, arg.UserID, arg.ID)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subject,
		&i.Instructions,
		&i.RejectedReason,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Expert,
	)
	return &i, err
}

const updateMonitorToReady = `-- name: UpdateMonitorToReady :one
update monitors
set expert = $1, status = 'ready', subject = $2, updated_at = now()
where user_id = $3 and id = $4
returning id, user_id, status, subject, instructions, rejected_reason, updated_at, created_at, expert
`

type UpdateMonitorToReadyParams struct {
	Expert    pgtype.Text
	Subject   pgtype.Text
	UserID    int64
	MonitorID int64
}

func (q *Queries) UpdateMonitorToReady(ctx context.Context, db DBTX, arg *UpdateMonitorToReadyParams) (*Monitor, error) {
	row := db.QueryRow(ctx, updateMonitorToReady,
		arg.Expert,
		arg.Subject,
		arg.UserID,
		arg.MonitorID,
	)
	var i Monitor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Subject,
		&i.Instructions,
		&i.RejectedReason,
		&i.UpdatedAt,
		&i.CreatedAt,
		&i.Expert,
	)
	return &i, err
}
