// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"
)

const activeUserIntegrations = `-- name: ActiveUserIntegrations :many
select
    'pushover'::notifier as name,
    exists(
        select 1 from pushover_user_tokens
        where user_id = $1
    ) as active
union
select
    'email'::notifier as name,
    true as active
`

type ActiveUserIntegrationsRow struct {
	Name   Notifier
	Active bool
}

func (q *Queries) ActiveUserIntegrations(ctx context.Context, db DBTX, userID int64) ([]*ActiveUserIntegrationsRow, error) {
	rows, err := db.Query(ctx, activeUserIntegrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ActiveUserIntegrationsRow
	for rows.Next() {
		var i ActiveUserIntegrationsRow
		if err := rows.Scan(&i.Name, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash, timezone, created_at, updated_at)
values ($1, $2, $3, $4, $5)
returning id, email, password_hash, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Timezone     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (*User, error) {
	row := db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, timezone, created_at, updated_at from users where id = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, db DBTX, id int64) (*User, error) {
	row := db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, timezone, created_at, updated_at from users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, db DBTX, email string) (*User, error) {
	row := db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
