// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_subscribers.sql

package models

import (
	"context"
)

const createEmailSubscriber = `-- name: CreateEmailSubscriber :exec
insert into email_subscribers (email)
values ($1)
on conflict (email) do nothing
`

func (q *Queries) CreateEmailSubscriber(ctx context.Context, db DBTX, email string) error {
	_, err := db.Exec(ctx, createEmailSubscriber, email)
	return err
}
