// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: llm_conversations.sql

package models

import (
	"context"
)

const addMessageToLLMConversation = `-- name: AddMessageToLLMConversation :exec
update llm_conversations
set messages = messages || $1, updated_at = now()
where id = $2
`

type AddMessageToLLMConversationParams struct {
	Message           LLMConversationMessages
	LlmConversationID int64
}

func (q *Queries) AddMessageToLLMConversation(ctx context.Context, db DBTX, arg *AddMessageToLLMConversationParams) error {
	_, err := db.Exec(ctx, addMessageToLLMConversation, arg.Message, arg.LlmConversationID)
	return err
}

const createLLMConversation = `-- name: CreateLLMConversation :one
insert into llm_conversations (user_id, source_type, source_id, created_at, updated_at)
values ($1, $2, $3, now(), now())
returning id, user_id, source_type, source_id, messages, created_at, updated_at
`

type CreateLLMConversationParams struct {
	UserID     int64
	SourceType LLMConversationsSource
	SourceID   int64
}

func (q *Queries) CreateLLMConversation(ctx context.Context, db DBTX, arg *CreateLLMConversationParams) (*LlmConversation, error) {
	row := db.QueryRow(ctx, createLLMConversation, arg.UserID, arg.SourceType, arg.SourceID)
	var i LlmConversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SourceType,
		&i.SourceID,
		&i.Messages,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
