// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type LLMConversationsSource string

const (
	LlmConversationsSourceCheck  LLMConversationsSource = "check"
	LlmConversationsSourceTriage LLMConversationsSource = "triage"
)

func (e *LLMConversationsSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LLMConversationsSource(s)
	case string:
		*e = LLMConversationsSource(s)
	default:
		return fmt.Errorf("unsupported scan type for LLMConversationsSource: %T", src)
	}
	return nil
}

type NullLLMConversationsSource struct {
	LLMConversationsSource LLMConversationsSource
	Valid                  bool // Valid is true if LLMConversationsSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLLMConversationsSource) Scan(value interface{}) error {
	if value == nil {
		ns.LLMConversationsSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LLMConversationsSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLLMConversationsSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LLMConversationsSource), nil
}

type MonitorCheckStatus string

const (
	MonitorCheckStatusScheduled MonitorCheckStatus = "scheduled"
	MonitorCheckStatusChecking  MonitorCheckStatus = "checking"
	MonitorCheckStatusFailed    MonitorCheckStatus = "failed"
	MonitorCheckStatusSuccess   MonitorCheckStatus = "success"
)

func (e *MonitorCheckStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorCheckStatus(s)
	case string:
		*e = MonitorCheckStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorCheckStatus: %T", src)
	}
	return nil
}

type NullMonitorCheckStatus struct {
	MonitorCheckStatus MonitorCheckStatus
	Valid              bool // Valid is true if MonitorCheckStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorCheckStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorCheckStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorCheckStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorCheckStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorCheckStatus), nil
}

type MonitorStatus string

const (
	MonitorStatusValidating MonitorStatus = "validating"
	MonitorStatusPreviewing MonitorStatus = "previewing"
	MonitorStatusRejected   MonitorStatus = "rejected"
	MonitorStatusReady      MonitorStatus = "ready"
	MonitorStatusActive     MonitorStatus = "active"
	MonitorStatusPaused     MonitorStatus = "paused"
)

func (e *MonitorStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MonitorStatus(s)
	case string:
		*e = MonitorStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for MonitorStatus: %T", src)
	}
	return nil
}

type NullMonitorStatus struct {
	MonitorStatus MonitorStatus
	Valid         bool // Valid is true if MonitorStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMonitorStatus) Scan(value interface{}) error {
	if value == nil {
		ns.MonitorStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MonitorStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMonitorStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MonitorStatus), nil
}

type Notifier string

const (
	NotifierEmail    Notifier = "email"
	NotifierPushover Notifier = "pushover"
)

func (e *Notifier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Notifier(s)
	case string:
		*e = Notifier(s)
	default:
		return fmt.Errorf("unsupported scan type for Notifier: %T", src)
	}
	return nil
}

type NullNotifier struct {
	Notifier Notifier
	Valid    bool // Valid is true if Notifier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifier) Scan(value interface{}) error {
	if value == nil {
		ns.Notifier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Notifier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Notifier), nil
}

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState
	Valid         bool // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type EmailSubscriber struct {
	ID        int64
	Email     string
	CreatedAt time.Time
}

type LlmConversation struct {
	ID         int64
	UserID     int64
	SourceType LLMConversationsSource
	SourceID   int64
	Messages   LLMConversationMessages
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
}

type Monitor struct {
	ID                    int64
	UserID                int64
	Status                MonitorStatus
	Subject               pgtype.Text
	RejectedReason        pgtype.Text
	UpdatedAt             time.Time
	CreatedAt             time.Time
	CheckFrequencyMinutes int32
}

type MonitorCheck struct {
	ID            int64
	MonitorID     int64
	Status        MonitorCheckStatus
	ScheduledFor  time.Time
	FailureReason pgtype.Text
	DoneAt        *time.Time
	Result        *CheckResult
}

type MonitorNotifier struct {
	ID        int64
	MonitorID int64
	Type      Notifier
	CreatedAt time.Time
}

type MonitorResult struct {
	ID                   int64
	MonitorID            int64
	Citations            *Citations
	CreatedAt            time.Time
	Feedback             pgtype.Text
	LastConfirmedCheckID int64
	LastConfirmedAt      time.Time
	Headline             string
	Subtitle             string
	Data                 MonitorUpdateData
}

type MonitorSchema struct {
	ID        int64
	MonitorID int64
	Data      MonitorSchemaData
	CreatedAt time.Time
}

type PushoverUserToken struct {
	Token     string
	UserID    int64
	CreatedAt time.Time
}

type RiverClient struct {
	ID        string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type RiverClientQueue struct {
	RiverClientID    string
	Name             string
	CreatedAt        time.Time
	MaxWorkers       int64
	Metadata         []byte
	NumJobsCompleted int64
	NumJobsRunning   int64
	UpdatedAt        time.Time
}

type RiverJob struct {
	ID           int64
	State        RiverJobState
	Attempt      int16
	MaxAttempts  int16
	AttemptedAt  *time.Time
	CreatedAt    time.Time
	FinalizedAt  *time.Time
	ScheduledAt  time.Time
	Priority     int16
	Args         []byte
	AttemptedBy  []string
	Errors       [][]byte
	Kind         string
	Metadata     []byte
	Queue        string
	Tags         []string
	UniqueKey    []byte
	UniqueStates pgtype.Bits
}

type RiverLeader struct {
	ElectedAt time.Time
	ExpiresAt time.Time
	LeaderID  string
	Name      string
}

type RiverMigration struct {
	Line      string
	Version   int64
	CreatedAt time.Time
}

type RiverQueue struct {
	Name      string
	CreatedAt time.Time
	Metadata  []byte
	PausedAt  *time.Time
	UpdatedAt time.Time
}

type SchemaMigration struct {
	Version int64
	Dirty   bool
}

type Session struct {
	ID        string
	CreatedAt time.Time
	ExpiresAt time.Time
	Data      []byte
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Timezone     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
