// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package models

import (
	"context"
	"time"
)

const countUsers = `-- name: CountUsers :one
select count(*)::bigint from users
`

func (q *Queries) CountUsers(ctx context.Context, db DBTX) (int64, error) {
	row := db.QueryRow(ctx, countUsers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :one
insert into users (email, password_hash, timezone, created_at, updated_at)
values ($1, $2, $3, $4, $5)
returning id, email, password_hash, timezone, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Timezone     string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateUser(ctx context.Context, db DBTX, arg *CreateUserParams) (*User, error) {
	row := db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Timezone,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUser = `-- name: GetUser :one
select id, email, password_hash, timezone, created_at, updated_at from users where id = $1 limit 1
`

func (q *Queries) GetUser(ctx context.Context, db DBTX, id int64) (*User, error) {
	row := db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, timezone, created_at, updated_at from users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, db DBTX, email string) (*User, error) {
	row := db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :one
update users
set password_hash = $1, updated_at = now()
where id = $2
returning id, email, password_hash, timezone, created_at, updated_at
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	UserID       int64
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, db DBTX, arg *UpdateUserPasswordHashParams) (*User, error) {
	row := db.QueryRow(ctx, updateUserPasswordHash, arg.PasswordHash, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserTimezone = `-- name: UpdateUserTimezone :one
update users
set timezone = $1, updated_at = now()
where id = $2
returning id, email, password_hash, timezone, created_at, updated_at
`

type UpdateUserTimezoneParams struct {
	Timezone string
	UserID   int64
}

func (q *Queries) UpdateUserTimezone(ctx context.Context, db DBTX, arg *UpdateUserTimezoneParams) (*User, error) {
	row := db.QueryRow(ctx, updateUserTimezone, arg.Timezone, arg.UserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Timezone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const userIntegrations = `-- name: UserIntegrations :many
select
    'pushover'::notifier as name,
    exists(
        select 1 from pushover_user_tokens
        where user_id = $1
    ) as configured
union
select
    'email'::notifier as name,
    true as configured
`

type UserIntegrationsRow struct {
	Name       Notifier
	Configured bool
}

func (q *Queries) UserIntegrations(ctx context.Context, db DBTX, userID int64) ([]*UserIntegrationsRow, error) {
	rows, err := db.Query(ctx, userIntegrations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*UserIntegrationsRow
	for rows.Next() {
		var i UserIntegrationsRow
		if err := rows.Scan(&i.Name, &i.Configured); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
